* cliphist (v0.5.5)

[[http://melpa.org/#/find-and-ctags][file:http://melpa.org/packages/cliphist-badge.svg]] [[http://stable.melpa.org/#/find-and-ctags][file:http://stable.melpa.org/packages/cliphist-badge.svg]]

Read data from clipboard managers at Linux and Mac,
- [[http://parcellite.sourceforge.net/][Parcellite]] on Linux
- [[http://clipit.sourceforge.net/][ClipIt]] on Linux
- [[https://github.com/TermiT/Flycut][Flycut]] on Mac
* Install
The easiest way is install from [[http://melpa.org][melpa]] using package manager.

If you install from source code, please place cliphist.el somewhere (say =~/.emacs/lisp=), and insert below code into =~/.emacs=:

#+begin_src elisp
(add-to-list 'load-path "~/.emacs.d/lisp/")
(require 'cliphist)
#+end_src

* Usage
Make sure the clipboard manager is running.

- =M-x cliphist-paste-item= to paste item from history. =C-u M-x cliphist-paste-item= rectangle paste item
- =M-x cliphist-select-item= to select item

* Advanced Tips (OPTIONAL)
** Tip 1
You can customize the behavior of cliphist-select-item,
#+begin_src elisp
(setq cliphist-select-item-callback
      (lambda (num str) (cliphist-copy-to-clipboard str)))
#+end_src
** Tip 2
If `cliphist-cc-kill-ring` is true, the selected/pasted string will be inserted into kill-ring.
#+begin_src elisp
(setq cliphist-cc-kill-ring t)
#+end_src
** Tip 3
You can tweak =cliphist-linux-clipboard-managers= to tell cliphist how to detect clipboard manager,
#+begin_src elisp
(setq cliphist-linux-clipboard-managers '("clipit" "parcellite"))
#+end_src
* Bug Report
Check [[https://github.com/redguardtoo/cliphist]].

* License
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see [[http://www.gnu.org/licenses/]].
